version: 1
symbols:
  - ADAUSDT
  - ARBUSDT
  - AVAXUSDT
  - BTCUSDT
  - DOGEUSDT
  - ETHUSDT
  - FARTCOINUSDT
  - HBARUSDT
  - INJUSDT
  - LINKUSDT
  - MATICUSDT
  - NEARUSDT
  - OPUSDT
  - PUMPFUNUSDT
  - SOLUSDT
  - XRPUSDT
